model_warmup {
  inputs [
    {
        key: "input1"
        value: {
          data_type: TYPE_FP32
          dims: 64
          dims: 120
          dims: 214
          random_data: true
        }
    }
  ]
  batch_size: 2
}
