model_warmup {
  inputs [
    {
        key: "input1"
        value: {
          data_type: TYPE_FP32
          dims: 3
          dims: 480
          dims: 854
          random_data: true
        }
    }
  ]
  batch_size: 2
}
