model_warmup {
  inputs [
    {
        key: "input1"
        value: {
          data_type: TYPE_FP32
          dims: 512
          dims: 60
          dims: 107
          random_data: true
        }
    }
  ]
  batch_size: 2
}
