model_warmup {
  inputs [
    {
        key: "INPUT__0"
        value: {
          data_type: TYPE_FP32
          dims: 1
          dims: 1024
          dims: 31
          dims: 31
          random_data: true
        }
    }
  ]
  batch_size: 1
}
