model_warmup {
  inputs [
    {
        key: "INPUT__0"
        value: {
          data_type: TYPE_FP32
          dims: 1
          dims: 256
          dims: 29
          dims: 29
          random_data: true
        }
    },
    {
        key: "INPUT__1"
        value: {
          data_type: TYPE_FP32
          dims: 1
          dims: 256
          dims: 5
          dims: 5
          random_data: true
        }
    }
  ]
  batch_size: 1
}
